INSERT INTO TSF_REC.CATEGORY (ID, CATEGORY_NAME_EN, CATEGORY_NAME_FR) VALUES (1, 'Employee', 'Salarié ');
INSERT INTO TSF_REC.CATEGORY (ID, CATEGORY_NAME_EN, CATEGORY_NAME_FR) VALUES (2, 'Professional Liberal', 'Professionnel Libéral');
INSERT INTO TSF_REC.CATEGORY (ID, CATEGORY_NAME_EN, CATEGORY_NAME_FR) VALUES (3, 'Trader', 'Commerçant');
INSERT INTO TSF_REC.CATEGORY (ID, CATEGORY_NAME_EN, CATEGORY_NAME_FR) VALUES (4, 'Artisan', 'Artisan');
INSERT INTO TSF_REC.CATEGORY (ID, CATEGORY_NAME_EN, CATEGORY_NAME_FR) VALUES (5, 'Farmer', 'Agriculteur');
INSERT INTO TSF_REC.CATEGORY (ID, CATEGORY_NAME_EN, CATEGORY_NAME_FR) VALUES (6, 'Retired', 'Retraité');