INSERT INTO TSF_REC.DETAIL_OFFER (ID, DESCRIPTION) VALUES (1, 'Accès à différents comptes de dépôt selon la devise de votre choix');
INSERT INTO TSF_REC.DETAIL_OFFER (ID, DESCRIPTION) VALUES (2, 'Une carte de débit nationale pour vos retraits et paiements en Tunisie');
INSERT INTO TSF_REC.DETAIL_OFFER (ID, DESCRIPTION) VALUES (3, 'Gestion de votre compte et de votre carte en ligne 24h/24 et 7j/7');
INSERT INTO TSF_REC.DETAIL_OFFER (ID, DESCRIPTION) VALUES (4, 'Gratuité sur la tous vos transferts reçus');
INSERT INTO TSF_REC.DETAIL_OFFER (ID, DESCRIPTION) VALUES (5, '50% de réduction sur les frais de mise à disposition');
INSERT INTO TSF_REC.DETAIL_OFFER (ID, DESCRIPTION) VALUES (6, 'Des taux préférentiels sur le crédit immobilier DARI FI BLEDI');
INSERT INTO TSF_REC.DETAIL_OFFER (ID, DESCRIPTION) VALUES (7, 'Accès à différents comptes de dépôt selon la devise de votre choix');
INSERT INTO TSF_REC.DETAIL_OFFER (ID, DESCRIPTION) VALUES (8, 'Une carte GOLD internationale pour vos paiements à l''étranger');
INSERT INTO TSF_REC.DETAIL_OFFER (ID, DESCRIPTION) VALUES (9, 'Gestion de votre compte et de votre carte en ligne 24h/24 et 7j/7');
INSERT INTO TSF_REC.DETAIL_OFFER (ID, DESCRIPTION) VALUES (10, 'Gratuité sur tous vos transferts reçus et vos prélèvements');
INSERT INTO TSF_REC.DETAIL_OFFER (ID, DESCRIPTION) VALUES (11, 'Réduction sur vos versements en devise');
INSERT INTO TSF_REC.DETAIL_OFFER (ID, DESCRIPTION) VALUES (12, '50% de réduction sur les frais de mise à disposition');
INSERT INTO TSF_REC.DETAIL_OFFER (ID, DESCRIPTION) VALUES (13, 'Des taux préférentiels sur le crédit immobilier DARI FI BLEDI');